export const GET_LESSON = 'GET_LESSON';
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS';
export const GET_LESSON_ERROR = 'GET_LESSON_ERROR';

export const POST_LESSON = 'POST_LESSON';
export const POST_LESSON_SUCCESS = 'POST_LESSON_SUCCESS';
export const POST_LESSON_ERROR = 'POST_LESSON_ERROR';

export const DELETE_LESSON = 'DELETE_LESSON';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
export const DID_DELETELES_ACTION = 'DID_DELETELES_ACTION';
export const DELETE_LESSON_ERROR = 'DELETE_LESSON_ERROR';

export const UPDATE_LESSON = 'UPDATE_LESSON';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';
export const DID_UPDATELES_ACTION = 'DID_UPDATELES_ACTION';
export const UPDATE_LESSON_ERROR = 'UPDATE_LESSON_ERROR';