import { StyleSheet, Dimensions } from "react-native";
import Sizes from "./Sizes";

const { width, height } = Dimensions.get('window');

const Styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    scrollView: {
        backgroundColor:'#dcdcdc'
    },
    selectedTextStyle: {
        height: 80,
        borderColor: 'gray',
        backgroundColor: 'transparent',
        justifyContent: 'center',
        width: '100%',
        color: 'black',
        fontSize: 20,
        paddingLeft: 10,
        marginTop: -2,
    },
    selectedTextStyle1: {
        height: 50,
        borderColor: 'gray',
        backgroundColor: 'transparent',
        justifyContent: 'center',
        width: '100%',
        color: 'black',
        fontSize: 20,
        paddingLeft: 10,
        marginTop: 15,
    },
    listTextStyle: {
        color: 'red',
        fontSize: 18,
        textAlign: 'left',
    },
    searchBarStyle: {
        marginBottom: 10,
        flexDirection: 'row',
        height: 40,
        shadowRadius: 1,
        shadowOpacity: 1.0,
        borderWidth: 1,
        shadowOffset: {
            width: 1,
            height: 1,
        },
        borderColor: '#303030',
        shadowColor: '#303030',
        borderRadius: 5,
        elevation: 1,
        marginHorizontal: 10,
    },
    placeHolderTextStyle: {
        color: 'red',
        padding: 10,
        textAlign: 'left',
        width: '99%',
        flexDirection: 'row',
    },
    dropDownIconStyle: {
        width: 10,
        height: 10,
        left: -40,
        // marginTop: 20,
    },
    dropDownIconStyle1: {
        width: 10,
        height: 10,
        left: -40,
        marginTop: 15,
    },
    pickerStyle: {
        backgroundColor: "#F2F4F4",
        shadowRadius: 0.5,
        shadowOpacity: 0.5,
        borderWidth: 0.5,
        shadowOffset: {
            width: 0.5,
            height: 0.5,
        },
        height: 50, 
        borderColor: '#303030',
        shadowColor: '#303030',
        borderRadius: 5,
        elevation: 0.5,
    },
    pickerStyle1: {
        height: 60,
        borderBottomColor: 'dodgerblue',
        borderBottomWidth: 2,
    },
    btnSave: {
        backgroundColor: '#ff9336',
        justifyContent: 'center',
        alignItems: 'center',
        width: 150,
        height: 40,
        borderRadius: 5,
        marginTop: Sizes.s20,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.85,
        elevation: 3,
    },
    inputFile: {
        padding: 10,
        justifyContent:'flex-end',
        alignItems: 'center',
        flexDirection: 'row',
        width: '90%',
        height: 50,
        backgroundColor: '#E5E7E9',
        borderColor: 'gray',
        borderRadius: 10,
        borderWidth: 1,
        marginTop: Sizes.s20,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.85,
        elevation: 3,
    },
    tableView: {
        alignItems:'center',
        width: '90%',
        height: 250,
        backgroundColor:'#E5E7E9',
        borderRadius: 10,
        borderWidth: 1,
        borderColor:'#1B4F72',
        marginVertical: Sizes.s20,
        shadowColor: '#000000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.85,
        elevation: 3,
    },
    input: {
        width: '95%',
        marginHorizontal: Sizes.s20,
        height: 50,
        backgroundColor: 'white',
        fontSize: 16,
        alignItems: 'center',
        textAlignVertical: "center",
        color: '#002168',
        borderWidth: 1,
        borderRadius: 5,
    }
    
});

export default Styles